version: '3.7'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend/logs:/backend/logs
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password  # Set the password for the user
    links:
      - database
    command: ["python", "app.py"]  

  frontend:
    build:
      context: ./frontend
    ports:
      - "8050:8050"

  database:
    build: ./database
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_ROOT_PASSWORD: 'password'  
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppassword"]  
      interval: 10s  
      timeout: 5s    
      retries: 3     
