version: '3'

services:
  backend:
    build:
      context: ./Backend
    depends_on:
      - database
    volumes:
      - ./backend/logs:/backend/logs
    ports:
      - "5001:5001" 

  frontend:
    build:
      context: ./dash-dashboard
    ports:
      - "8050:8050"  

  database:
    image: mysql:8.3.0
    volumes:
      - ./database:/docker-entrypoint-initdb.d
