name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build Docker image
      - name: Build Docker image
        run: docker build -t competitive-pricing-analysis .

      # Run Docker container for testing
      - name: Run tests in Docker container
        run: |
          docker run --rm competitive-pricing-analysis pytest tests
